// Generated by CoffeeScript 1.10.0
(function() {
  var coffee, compass, concatCss, glob, gulp, haml, htmlmin, imagemin, minifyCSS, please, plumber, pngquant, prefix, rename, sass, slim, sourcemaps, spritesmith, stylus, uglify, uncss, zip;

  gulp = require('gulp');

  rename = require('gulp-rename');

  concatCss = require('gulp-concat-css');

  minifyCSS = require('gulp-minify-css');

  plumber = require('gulp-plumber');

  haml = require('gulp-ruby-haml');

  coffee = require('gulp-coffee');

  sourcemaps = require('gulp-sourcemaps');

  compass = require('gulp-compass');

  imagemin = require('gulp-imagemin');

  pngquant = require('imagemin-pngquant');

  uncss = require('gulp-uncss');

  uglify = require('gulp-uglify');

  glob = require('glob');

  htmlmin = require('gulp-htmlmin');

  zip = require('gulp-zip');

  spritesmith = require('gulp.spritesmith');

  slim = require('gulp-slim');

  sass = require('gulp-sass');

  stylus = require('gulp-stylus');

  prefix = require('gulp-autoprefixer');

  please = require('gulp-pleeease');

  gulp.task('coffee', function() {
    return gulp.src('./client/app/javascripts/**/*.coffee').pipe(plumber({
      errorHandler: function(error, file) {
        console.log(error.message);
        return this.emit('end');
      }
    })).pipe(sourcemaps.init()).pipe(coffee({
      bare: false
    })).pipe(sourcemaps.write('./')).pipe(gulp.dest('./client/app/javascripts/'));
  });

  gulp.task('imagemin', function() {
    return gulp.src('./client/app/images/**/*').pipe(imagemin({
      progressive: true,
      svgoPlugins: [
        {
          removeViewBox: false
        }
      ],
      use: [pngquant()]
    })).pipe(gulp.dest('./client/app/images'));
  });

  gulp.task('watchConsole', function() {
    var exec, watch;
    exec = require('child_process').exec;
    watch = require('gulp-watch');
    return watch('./client/app/images/**/*.{jpg,jpeg,png,gif}', function() {
      return exec('chmod 755 -R ./app/images');
    });
  });

  gulp.task('sass', function() {
    return gulp.src('./client/app/stylesheets/**/*.scss').pipe(plumber({
      errorHandler: function(error, file) {
        console.log(error.message);
        return this.emit('end');
      }
    })).pipe(sourcemaps.init()).pipe(sass()).pipe(sourcemaps.write('./')).pipe(gulp.dest('./client/app/stylesheets'));
  });

  gulp.task('please', function() {
    return gulp.src('./client/app/stylesheets/**/*.css').pipe(plumber({
      errorHandler: function(error, file) {
        console.log(error.message);
        return this.emit('end');
      }
    })).pipe(please({
      'minifier': false,
      'browsers': ['last 6 versions', 'Android 2.3', 'ie 7', 'ie 8', 'ie 9', 'ie 10', 'ie 11'],
      'autoprefixer': true,
      'filters': true,
      'oldIE': true,
      'rem': true,
      'pseudoElements': true,
      'opacity': true,
      'import': true,
      'mqpacker': true,
      'next': true
    })).pipe(gulp.dest('./client/app/stylesheets'));
  });

  gulp.task('sprite', function() {
    var spriteData;
    spriteData = gulp.src('./client/app/images/sprite/*.*').pipe(spritesmith({
      imgName: '../images/sprite.png',
      cssName: '_sprite.scss',
      padding: 2
    }));
    spriteData.img.pipe(gulp.dest('./client/app/images/'));
    return spriteData.css.pipe(gulp.dest('./client/app/stylesheets/'));
  });

  gulp.task('watch', function() {
    gulp.watch('./client/app/stylesheets/**/*.scss', ['sass']);
    gulp.watch('./client/app/stylesheets/**/*.scss', ['sprite']);
    return gulp.watch('./client/app/javascripts/**/*.coffee', ['coffee']);
  });

  gulp.task('default', ['sass', 'sprite', 'coffee', 'watch']);

  gulp.task('stylus:admin', function() {
    return gulp.src('./client/app/admin/styles/application.styl').pipe(plumber({
      errorHandler: function(error, file) {
        console.log(error.message);
        return this.emit('end');
      }
    })).pipe(stylus({
      'include css': true,
      sourcemap: {
        inline: true,
        sourceRoot: '.',
        basePath: './client/app/admin/styles'
      }
    })).pipe(please({
      'minifier': false,
      "autoprefixer": {
        'browsers': ['last 6 versions', 'Android 4', 'ie 9', 'ie 10', 'ie 11']
      },
      'filters': true,
      'oldIE': true,
      'rem': true,
      'pseudoElements': true,
      'opacity': true,
      'import': true,
      'mqpacker': true,
      'next': true,
      preserveHacks: true,
      removeAllComments: true,
      sourcemaps: true
    })).pipe(gulp.dest('./client/app/admin/styles'));
  });

  gulp.task('sprite:admin', function() {
    var spriteData;
    spriteData = gulp.src('./client/app/admin/images/sprite/*.*').pipe(spritesmith({
      imgName: './sprite.png',
      cssName: '_sprite.styl',
      padding: 2
    }));
    spriteData.img.pipe(gulp.dest('./client/app/admin/images/'));
    return spriteData.css.pipe(gulp.dest('./client/app/admin/styles/utilities/'));
  });

  gulp.task('watch:admin', function() {
    gulp.watch('./client/app/admin/styles/**/*.styl', ['stylus:admin']);
    return gulp.watch('./client/app/admin/styles/**/_sprite.slyl', ['sprite:admin']);
  });

  gulp.task('default:admin', ['sprite:admin', "stylus:admin", 'watch:admin']);

}).call(this);

//# sourceMappingURL=gulpfile.js.map
